// GENERAL OPTIONS
export const SHOW_DETAILED_VIEW = true;

// DIMENSIONS
export const TITLE_HEIGHT = 2.6;
export const SUBTITLE_HEIGHT = 7;
export const SUBTITLE_MARGIN_BOTTOM = 1;
export const TITLE_MARGIN_BOTTOM = 0.5;
export const TITLE_OFFSET = TITLE_HEIGHT + TITLE_MARGIN_BOTTOM;
export const SUBTITLE_OFFSET = SUBTITLE_HEIGHT + SUBTITLE_MARGIN_BOTTOM;
export const CONTROLS_HEIGHT = 3;

export const HEADER_HEIGHT = 7.5; //vw
export const HEADER_MARGIN_TOP = 1; //vw
export const HEADER_MARGIN_BOTTOM = 2; //vw
export const HEADER_OFFSET = HEADER_MARGIN_TOP + HEADER_HEIGHT + HEADER_MARGIN_BOTTOM;


export const CASE_HEADER_HEIGHT = 1.7; //vw

export const CASE_MARGIN_BOTTOM = 1.4;//vw

export const ACTION_ROW_SIZE = 1; //vw
export const ACTION_MARGIN_LEFT = 1; //vw
export const ACTION_PADDING_LEFT = 1;
export const ACTION_MARGIN_RIGHT = 1;
export const ACTION_PADDING_RIGHT = 1;

export const SHORTINFO_LABEL_SIZE = 0.7;


export const ACTION_PADDING_BOTTOM = ACTION_ROW_SIZE;

export const CONNECTION_STROKE_SIZE = 2;//vw

export const DATASOURCE_AND_DATAPURPOSE_ROW_SIZE = 1.1;
export const DATASOURCE_AND_DATAPURPOSE_MARGIN_TOP = 0.2;//DATASOURCE_AND_DATAPURPOSE_ROW_SIZE;
export const DATASOURCE_AND_DATAPURPOSE_PADDING_TOP = 0.2;//DATASOURCE_AND_DATAPURPOSE_ROW_SIZE;


